### ISSUE TITLE
sed and awk issues in "start.sh" when restarting container 

### ISSUE THREAD

**Issue by eye-v** [driket/docker-glpi#1]
In case if container was restarted then "/etc/apache2/sites-enabled/000-default.conf" is become wrong after it. 
If "000-default.conf" already have "DocumentRoot /var/www/html/glpi" strint in it, then sed command will turn it to "DocumentRoot /var/www/html/glpi/glpi"
and if "ServerSignature Off" exists, awk just add another copy of it below.

Maybe it will be better to replace sed command to something like this:
"sed -i -- 's/DocumentRoot .*/DocumentRoot \/var\/www\/html\/glpi/g' $VHOST"
and add another sed command, before awk, to delete  "ServerSignature Off" if exists:
"sed -i -- '/ServerSignature /d' $VHOST"

**Comment by driket** [comment]
I've pushed this changes in the start.sh config. It should do the job correctly now.

Thanks for you help.

Cédric.
